### ISSUE TITLE
Incomplete statement on line 45

### ISSUE THREAD

**Issue by lacymooretx** [mgbolts/fpbx-yealink-xmlcontacts#1]
`$results = $db->$type("SELECT cen.number, cge.displayname, cen.type, cen.E164 FROM contactmanager_group_entries AS cge LEFT JOIN contactmanager_en$`

I'm not sure exactly what is supposed to be at the end of the line, but I think it was cut off.

**Comment by mgbolts** [comment]
Yes, sorry about that. Should be fixed now, let me know if you have any issues.

**Comment by susedv** [comment]
Still doesn't work, I think it should be "cen.E164" and not "cen E164".
But there are more bugs:
`PHP Parse error:  syntax error, unexpected end of file in /var/www/html/cm_to_yl_ab_L2.php on line 137`
It also looks like the variable $extensions gets never assigned.

EDIT:
I believe I have fixed all bugs and added a new option for setting the contact group in the URL, you can apply my patch:

```
From a53f9586ee26e85af5efd99e240f65fa8b8d4575 Mon Sep 17 00:00:00 2001
From: Firstname Lastname <firstname.lastname@some-domain.com>
Date: Thu, 19 Dec 2019 13:53:52 +0100
Subject: [PATCH] Fixed some critical bugs and added an option to specify the
 contact group in the URL.

---
 cm_to_yl_ab_L2.php | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

diff --git a/cm_to_yl_ab_L2.php b/cm_to_yl_ab_L2.php
index ecb7385..fde2861 100644
--- a/cm_to_yl_ab_L2.php
+++ b/cm_to_yl_ab_L2.php
@@ -13,9 +13,10 @@ https://mangolassi.it/topic/18647/freepbx-contact-manager-to-yealink-address-boo
 // c) Add labels to each phone number
 // e) Use E164 number convention
 // f) Allow the number labels to be customized.
+// g) Now you can specify the contact group in the URL, ex.: https://[MYHOSTNAME]/cm_to_yl_ab_L2.php?cgroup=User%20Manager%20Group
 
 // Edit this varibale to match the name of hte group in Contact Manager
-$contact_manager_group = "User Manager Group";
+$contact_manager_group = isset($_GET['cgroup']) ? $_GET['cgroup'] : "User Manager Group";
 
 header("Content-Type: text/xml");
 
@@ -42,7 +43,7 @@ $db = DB::connect($datasource); // attempt connection
 
 $type="getAll";
 // This pulls every number in contact maanger that is part of the group specified by $contact_manager_group
-$results = $db->$type("SELECT cen.number, cge.displayname, cen.type, cen E164 FROM contactmanager_group_entries AS cge LEFT JOIN contactmanager_entry_numbers AS cen ON cen.entryid = cge.id WHERE cge.groupid = (SELECT cg.id FROM contactmanager_groups AS cg WHERE cg.name = '$contact_manager_group') ORDER BY cge.displayname ASC;", null);
+$results = $db->$type("SELECT cen.number, cge.displayname, cen.type, cen.E164 FROM contactmanager_group_entries AS cge LEFT JOIN contactmanager_entry_numbers AS cen ON cen.entryid = cge.id WHERE cge.groupid = (SELECT cg.id FROM contactmanager_groups AS cg WHERE cg.name = '$contact_manager_group') ORDER BY cge.displayname ASC;", null);
 
 //dump the result into an array.
 foreach($results as $result){
@@ -75,7 +76,9 @@ foreach($results as $result){
         $result[2] = "Home";   // this is the label that will display on the phone
         $sortorder = 5;  // change this number to change its order in the list
     }
-
+    
+    $extensions[] = array($result[0],$result[1],$result[2]);
+}
 // This sorts the extensions array by two fields, the display name and then the sort order field
 // To change the sort order of the labels, change the sort order number in the if statements above..
 
-- 
2.16.2.windows.1
```

**Comment by sorvani** [comment]
This repo is still broken.

I have now backported your changes into my original. It is still in my testing branch as I do not have the sub-sort by label working yet.

https://github.com/sorvani/freepbx-helper-scripts/tree/Testing/ContactManager_to_Yealink_AddressBook

**Comment by susedv** [comment]
fhg



System + Service Achim Sinsel
Dietrich-Bonhoeffer-Str. 3
D-67346 Speyer

Tel.: +49 (0) 7275 61 79 51
Durchwahl: 
Fax: +49 (0) 7275 61 85 01
E-Mail: 
Web: http://www.sus-edv.com
Geschäftsführer: Achim Sinsel, Ust.-ID Nr.: DE 166 280 054.
This repo is still broken.

I have now backported your changes into my original. It is still in my testing branch as I do not have the sub-sort by label working yet.

https://github.com/sorvani/freepbx-helper-scripts/tree/Testing/ContactManager_to_Yealink_AddressBook
